Fundraise.MvcExample/Models/FundraisersViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fundraise.MvcExample.Models
{
    public class FundraisersViewModel // same as AdminViewModel? 
    {
        public IList<CampaignViewModel> Campaigns { get; set; }
    }
}

Fundraise.MvcExample/Controllers/FundraiserController.cs
using Fundraise.Core.Entities;
using Fundraise.MvcExample.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MediatR;
using Fundraise.Requests.Campaign;
using Fundraise.Requests;

namespace Fundraise.MvcExample.Controllers
{
    public class FundraiserController : Controller
    {
        private readonly IMediator _mediator;

        public FundraiserController(IMediator mediator)
        {
            _mediator = mediator;
        }

        // GET: Fundraiser
        public ActionResult Index(Guid? id)
        {
            if (!id.HasValue)
            {
                var campaigns = _mediator.Send(new GetAll()).Result;

                var model = new FundraisersViewModel();
                model.Campaigns = AutoMapper.Mapper.Map<List<Campaign>, List<CampaignViewModel>>(campaigns);
                foreach (var campaign in model.Campaigns)
                {
                    var fundraisers = _mediator.Send(new Requests.Fundraiser.GetByCampaignId(campaign.Id)).Result;
                    campaign.Fundraisers = AutoMapper.Mapper.Map<List<Fundraiser>, List<FundraiserViewModel>>(fundraisers);
                }

                return View(model);
            }

            var request = new Requests.Fundraiser.GetById(id.Value);
            var fundraiser = _mediator.Send(request).Result;
            if (fundraiser == null)
                return HttpNotFound();

            var fundraiserViewModel = AutoMapper.Mapper.Map<Fundraiser, FundraiserViewModel>(fundraiser);
            var donations = _mediator.Send(new Requests.Donation.GetByFundraiserId(request.Id)).Result;
            fundraiserViewModel.Donations = AutoMapper.Mapper.Map<List<Donation>, List<DonationViewModel>>(donations);

            return View("Detail", fundraiserViewModel);
        }

        [HttpGet]
        public ActionResult Donate(Guid id)
        {
            var request = new Requests.Fundraiser.GetById(id);
            var fundraiser = _mediator.Send(request).Result;
            var fundraiserViewModel = AutoMapper.Mapper.Map<Fundraiser, FundraiserFormViewModel>(fundraiser);

            return View(fundraiserViewModel);
        }

        [HttpPost]
        public ActionResult Donate(DonateFormViewModel model)
        {
            Donate request = new Donate()
            {
                DonationAmount = model.DonationAmount,
                FundraiserId = model.FundraiserId,
                DonorDisplayName = model.DonorDisplayName,
                StripeToken = model.StripeToken
            };
            request.UserId = User.Identity.IsAuthenticated ? User.Identity.GetUserId() : string.Empty;
            bool success = _mediator.Send(request).Result;

            var fundraiserViewModel = new FundraiserFormViewModel()
            {
                Name = "Need to get Fundraiser name?" // todo
            };
            // AutoMapper.Mapper.Map<Fundraiser, FundraiserFormViewModel>(fundraiser);
            return View("Thanks", fundraiserViewModel);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var campaigns = _mediator.Send(new GetAll()).Result;

            ViewBag.CampaignDropDown = new SelectList(campaigns, "Id", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult Create(FundraiserFormViewModel model)
        {
            if (User.Identity.IsAuthenticated)
            {
                var request = new Requests.Fundraiser.Create()
                {
                    Name = model.Name,
                    CampaignId = model.CampaignId,
                    UserId = User.Identity.GetUserId()
                };
                Guid fundraiserId = _mediator.Send(request).Result;
                return RedirectToAction("Index", new { id = fundraiserId });
            }
            else
            {
                return RedirectToAction("Create");
            }
        }
    }
}

Fundraise.MvcExample/Views/Fundraiser/Create.cshtml
@using Fundraise.MvcExample.Models
@model FundraiserFormViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="page-header">
    <h1>Create Fundraiser</h1>
</div>
<div class="row">
    <form id="campaignForm" novalidate action="@Url.Action("Create", "Fundraiser")" method="post">
        <div class="col-lg-10">
            <div class="form-group">
                @{
                    SelectList list = ViewBag.CampaignDropDown;
                }
                Campaign:
                @Html.DropDownList("CampaignId", list, "-- SELECT ONE --")<br />
            </div>
            <div class="form-group">
                @Html.LabelFor(p => p.Name)
                @Html.EditorFor(p => p.Name)
                @Html.ValidationMessageFor(p => p.Name, "*")
            </div>
            <div class="form-group">
                @Html.LabelFor(p => p.Description)
                @Html.EditorFor(p => p.Description)
            </div>
            <div class="form-group pull-right">
                <input type="hidden" name="IsActive" value="true" />
                <input type="submit" class="btn btn-success" value="Save" />
            </div>
        </div>
    </form>
</div>

Fundraise.MvcExample/Views/Fundraiser/Detail.cshtml
@using Fundraise.MvcExample.Models
@model FundraiserViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="page-header">
    <h1>@Model.Name</h1>
    <h2>Donations</h2>
    <ul>
        @foreach (var donation in Model.Donations)
        {
            <li>@donation.DonorDisplayName - $@donation.Amount</li>
        }
    </ul>
    @Html.ActionLink("Donate", "Donate", new { id = Model.Id }, new { @class = "btn btn-default" })
</div>

Fundraise.MvcExample/Views/Fundraiser/Donate.cshtml
@using Fundraise.MvcExample.Models
@model FundraiserFormViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="page-header">
    <h1>Donate to @Model.Name</h1>
</div>
<div class="row">

    <form action="@Url.Action("Donate", "Fundraiser")" method="post" id="payment-form">
        <div class="col-lg-10">
            <div class="form-row">
                <label for="DonationAmount">Amount</label>
                <input type="number" name="DonationAmount" />
            </div>
            <div class="form-row">
                <label for="card-element">
                    Credit or debit card
                </label>
                <div id="card-element">
                    <!-- a Stripe Element will be inserted here. -->
                </div>

                <!-- Used to display form errors -->
                <div id="card-errors" role="alert"></div>
            </div>
            <div class="form-row">
                <label for="DonorDisplayName">Name</label>
                <input type="text" name="DonorDisplayName" />
            </div>
            <input type="hidden" name="FundraiserId" value="@Model.Id" />
            <input id="stripe-token" type="hidden" name="stripeToken" />
            <input type="submit" class="submit" value="Submit Payment">
        </div>
    </form>
    <script type="text/javascript">
        var stripe = Stripe('@System.Configuration.ConfigurationManager.AppSettings["StripePublishableKey"]');
        var elements = stripe.elements();
        var card = elements.create('card');
        card.mount('#card-element');

        // Handle real-time validation errors from the card Element.
        card.addEventListener('change', function (event) {
            var displayError = document.getElementById('card-errors');
            if (event.error) {
                displayError.textContent = event.error.message;
            } else {
                displayError.textContent = '';
            }
        });

        // Handle form submission
        var form = document.getElementById('payment-form');
        form.addEventListener('submit', function (event) {
            if ($('#stripe-token').val() == '') {
                event.preventDefault();

                stripe.createToken(card).then(function (result) {
                    if (result.error) {
                        // Inform the user if there was an error
                        var errorElement = document.getElementById('card-errors');
                        errorElement.textContent = result.error.message;
                    } else {
                        // Send the token to your server
                        $('#stripe-token').val(result.token.id);
                        console.log(result.token.id);
                    }
                });
            } else {
                console.log($('#stripe-token').val());
            }
        });
    </script>
</div>
@section headSection {
}

Fundraise.MvcExample/Views/Fundraiser/Index.cshtml
@using Fundraise.MvcExample.Models
@model FundraisersViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="page-header">
    <h1>Fundraisers</h1>
</div>
<ul class="list-group">
    @foreach (var campaign in Model.Campaigns)
    {
        <li class="list-group-item">
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading"><h3>@campaign.Name</h3></div>
                <div class="panel-body">
                    @if (campaign.Fundraisers.Count > 0)
                {
                        <ul class="list-group">
                            @foreach (var fundraiser in campaign.Fundraisers)
                            {
                                <li class="list-group-item">@Html.ActionLink(fundraiser.Name, "Index", "Fundraiser", new { id = fundraiser.Id }, null)</li>
                            }
                        </ul>
                    }
                    else
                    {
                        <p class="h4">This campaign has no fundraisers.</p>
                    }
                </div>
            </div>
        </li>
    }
</ul>

Fundraise.MvcExample/Views/Fundraiser/Thanks.cshtml
@using Fundraise.MvcExample.Models
@model FundraiserFormViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="page-header">
    <h1>Thank you for your donation</h1>
</div>
<div class="row">


</div>
@section headSection {
}